default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: mypassword
  pool: 5
development:
  <<: *default
  database: rails_app_development
test:
  <<: *default
  database: rails_app_test
production:
  <<: *default
  database: rails_app_production
  username: postgres
  password: mypassword